[profile.default]
solc-version = "0.8.17"
bytecode_hash = "none"
optimizer_runs = 1000000

[profile.intense.fuzz]
runs = 10000

[rpc_endpoints]
local = "http://localhost:8545"
wallaby = "https://wallaby.node.glif.io/rpc/v0"
